
import "./globals.css";
import {Inter} from "next/font/google"



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  weight: ['400'],
  subsets: ['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
